// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Models;

namespace Repository.Migrations
{
    [DbContext(typeof(NotationContext))]
    [Migration("20201206011413_Migration_Inicial")]
    partial class Migration_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Models.ProjectTeam", b =>
                {
                    b.Property<int>("idProjectTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDPROJECTTEAM")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idProject")
                        .HasColumnName("IDPROJECT")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnName("IDUSER")
                        .HasColumnType("int");

                    b.HasKey("idProjectTeam");

                    b.ToTable("ProjectTeam");
                });

            modelBuilder.Entity("Repository.Models.ProjectUser", b =>
                {
                    b.Property<int>("idProjectUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDPROJECTUSER")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjectidProject")
                        .HasColumnType("int");

                    b.Property<int>("idProject")
                        .HasColumnName("IDPROJECT")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnName("IDUSER")
                        .HasColumnType("int");

                    b.HasKey("idProjectUser");

                    b.HasIndex("ProjectidProject");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Address", b =>
                {
                    b.Property<int>("idAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDADDRESS")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Countrie")
                        .HasColumnName("COUNTRIE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnName("LATITUDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnName("LONGITUDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnName("NUMBER")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnName("STREET")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAddress");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Attach", b =>
                {
                    b.Property<int>("idAttach")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDATTACH")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Blob")
                        .HasColumnName("BLOB")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ExecutionTaskidTask")
                        .HasColumnType("int");

                    b.Property<int?>("ImpedimentidImpediment")
                        .HasColumnType("int");

                    b.Property<int?>("KnowledgeidKnowledge")
                        .HasColumnType("int");

                    b.Property<int?>("NotationidNotation")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnName("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnName("TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAttach");

                    b.HasIndex("ExecutionTaskidTask");

                    b.HasIndex("ImpedimentidImpediment");

                    b.HasIndex("KnowledgeidKnowledge");

                    b.HasIndex("NotationidNotation");

                    b.ToTable("AttachT");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Backlog", b =>
                {
                    b.Property<int>("idBacklog")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDBACKLOG")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnName("CATEGORY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estimate")
                        .HasColumnName("ESTIMATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExecutionTaskidTask")
                        .HasColumnType("int");

                    b.Property<string>("Importance")
                        .HasColumnName("IMPORTANCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precedence")
                        .HasColumnName("PRECEDENCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Story")
                        .HasColumnName("STORY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idMockup")
                        .HasColumnName("IDMOCKUP")
                        .HasColumnType("int");

                    b.Property<int>("idProject")
                        .HasColumnName("IDPROJECT")
                        .HasColumnType("int");

                    b.Property<int>("idStatus")
                        .HasColumnName("IDSTATUS")
                        .HasColumnType("int");

                    b.HasKey("idBacklog");

                    b.HasIndex("ExecutionTaskidTask");

                    b.ToTable("Backlog");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.ExecutionTask", b =>
                {
                    b.Property<int>("idTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDTASK")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Effort")
                        .HasColumnName("EFFORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImpedimentidImpediment")
                        .HasColumnType("int");

                    b.Property<int?>("KnowledgeidKnowledge")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectidProject")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnName("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnName("WEIGHT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idProject")
                        .HasColumnName("IDPROJECT")
                        .HasColumnType("int");

                    b.Property<int>("idStatus")
                        .HasColumnName("IDSTATUS")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnName("IDUSER")
                        .HasColumnType("int");

                    b.HasKey("idTask");

                    b.HasIndex("ImpedimentidImpediment");

                    b.HasIndex("KnowledgeidKnowledge");

                    b.HasIndex("ProjectidProject");

                    b.ToTable("ExecutionTask");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Impediment", b =>
                {
                    b.Property<int>("idImpediment")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDIMPEDIMENT")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnName("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idUser")
                        .HasColumnName("IDUSER")
                        .HasColumnType("int");

                    b.HasKey("idImpediment");

                    b.ToTable("Impediment");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Knowledge", b =>
                {
                    b.Property<int>("idKnowledge")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDKNOWLEDGE")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnName("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idKnowledge");

                    b.ToTable("Knowledge");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Mockup", b =>
                {
                    b.Property<int>("idMockup")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDMOCKUP")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Blob")
                        .HasColumnName("BLOB")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .HasColumnName("TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMockup");

                    b.ToTable("Mockup");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Notation", b =>
                {
                    b.Property<int>("idNotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDNOTATION")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionCard")
                        .HasColumnName("POSITIONCARD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnName("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idProject")
                        .HasColumnName("IDPROJECT")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnName("IDUSER")
                        .HasColumnType("int");

                    b.HasKey("idNotation");

                    b.ToTable("Notation");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Profile", b =>
                {
                    b.Property<int>("idProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDPROFILE")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDate")
                        .HasColumnName("BIRTHDATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnName("SURNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProfile");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Project", b =>
                {
                    b.Property<int>("idProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDPROJECT")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentDone")
                        .HasColumnName("PERCENTDONE")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnName("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProject");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Status", b =>
                {
                    b.Property<int>("idStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDSTATUS")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnName("TIPO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idStatus");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Team", b =>
                {
                    b.Property<int>("idTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDTEAM")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTeam");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDUSER")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .HasColumnName("LOGIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnName("PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idAddress")
                        .HasColumnName("IDADDRESS")
                        .HasColumnType("int");

                    b.Property<int>("idProfile")
                        .HasColumnName("IDPROFILE")
                        .HasColumnType("int");

                    b.HasKey("idUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Repository.Models.ProjectUser", b =>
                {
                    b.HasOne("TeamNotationAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectidProject");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Attach", b =>
                {
                    b.HasOne("TeamNotationAPI.Models.ExecutionTask", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ExecutionTaskidTask");

                    b.HasOne("TeamNotationAPI.Models.Impediment", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ImpedimentidImpediment");

                    b.HasOne("TeamNotationAPI.Models.Knowledge", null)
                        .WithMany("Attachments")
                        .HasForeignKey("KnowledgeidKnowledge");

                    b.HasOne("TeamNotationAPI.Models.Notation", null)
                        .WithMany("Attachments")
                        .HasForeignKey("NotationidNotation");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.Backlog", b =>
                {
                    b.HasOne("TeamNotationAPI.Models.ExecutionTask", null)
                        .WithMany("Backlogs")
                        .HasForeignKey("ExecutionTaskidTask");
                });

            modelBuilder.Entity("TeamNotationAPI.Models.ExecutionTask", b =>
                {
                    b.HasOne("TeamNotationAPI.Models.Impediment", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ImpedimentidImpediment");

                    b.HasOne("TeamNotationAPI.Models.Knowledge", null)
                        .WithMany("Tasks")
                        .HasForeignKey("KnowledgeidKnowledge");

                    b.HasOne("TeamNotationAPI.Models.Project", null)
                        .WithMany("ExecutionTasks")
                        .HasForeignKey("ProjectidProject");
                });
#pragma warning restore 612, 618
        }
    }
}
