CREATE TABLE [dbo].[Address] (
    [IDADDRESS] INT            IDENTITY (1, 1) NOT NULL,
    [NUMBER]    INT            NOT NULL,
    [STREET]    NVARCHAR (MAX) NULL,
    [COUNTRIE]  NVARCHAR (MAX) NULL,
    [LATITUDE]  NVARCHAR (MAX) NULL,
    [LONGITUDE] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED ([IDADDRESS] ASC)
);

