CREATE TABLE [dbo].[Knowledge] (
    [IDKNOWLEDGE] INT            IDENTITY (1, 1) NOT NULL,
    [TITLE]       NVARCHAR (MAX) NULL,
    [DESCRIPTION] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Knowledge] PRIMARY KEY CLUSTERED ([IDKNOWLEDGE] ASC)
);

