CREATE TABLE [dbo].[Profile] (
    [IDPROFILE] INT            IDENTITY (1, 1) NOT NULL,
    [NAME]      NVARCHAR (MAX) NULL,
    [SURNAME]   NVARCHAR (MAX) NULL,
    [BIRTHDATE] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Profile] PRIMARY KEY CLUSTERED ([IDPROFILE] ASC)
);

