CREATE TABLE [dbo].[ProjectTeam] (
    [IDPROJECTTEAM] INT IDENTITY (1, 1) NOT NULL,
    [IDUSER]        INT NOT NULL,
    [IDPROJECT]     INT NOT NULL,
    CONSTRAINT [PK_ProjectTeam] PRIMARY KEY CLUSTERED ([IDPROJECTTEAM] ASC)
);

