CREATE TABLE [dbo].[Status] (
    [IDSTATUS]    INT            IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NULL,
    [TIPO]        NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Status] PRIMARY KEY CLUSTERED ([IDSTATUS] ASC)
);

